version: '3'
services:

  api:
    build:  
      context: api/.
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:  
      context: backend/.
    ports:
      - "4000:4000"
    restart: always

  node:
    build:  
      context: node/.
    ports:
      - "5000:5000"
    restart: always
    
